services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php
    build: 
      context: .
      dockerfile: ./docker/php/DockerFile
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - composer

  composer:
    image: composer:latest
    container_name: composer-installer
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    command: ["composer", "install"]

  database:
    container_name: database
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: EventsDB
      MARIADB_USER: admin
      MARIADB_PASSWORD: secret
    volumes:
      - database_data:/var/lib/mysql
    

volumes:
  database_data: {}